# Generated by Django 4.0.4 on 2022-07-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='static/uploads/')),
            ],
        ),
    ]
