# Generated by Django 4.0.4 on 2022-07-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='type',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=100, null=True),
        ),
    ]
