# Generated by Django 4.0.4 on 2022-07-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projetos_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='type',
            field=models.CharField(choices=[('app', 'app'), ('web', 'web'), ('card', 'card')], max_length=100, null=True),
        ),
    ]
