# Generated by Django 4.0.3 on 2022-05-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_create_at_patient_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
